### ISSUE TITLE
Cannot start dc_eventlog

### ISSUE THREAD

**Issue by ooii** [ebaauw/homebridge-hue-utils#1]
When trying to start dc_eventlog, I have the following error:
```
error: Unexpected server response: 200
connection closed
```

I'm running version `0.4.8` and I'm starting it like this `dc_eventlog -sH 192.168.1.11:8888`. 
Note that I'm running deConz `2.0.20` and that when I try to access `192.168.1.11:8888` on my browser, I'm redirected to the `Phoscon` web app (`http://192.168.1.11:8888/pwa/login.html`).

**Comment by ebaauw** [comment]
You need to specify the web socket port, not the web server (REST API) port.  By default it’s 443; you can check it by `ph get /config/websocketport`.

**Comment by ooii** [comment]
Thank you.
