### ISSUE TITLE
Is ph_rules deprectated?

### ISSUE THREAD

**Issue by ooii** [ebaauw/homebridge-hue-utils#2]
Hi @ebaauw,

I went through the code of `ph_rules` which seems to include some interesting functions. Are they included in the `homebridge-hue-utils` of not? I cannot find them.
Also, do you have any explanation or example of using `ph_rules` and `ph_sensors`? I'm planning to start my setting from scratch and if they can make my life easier, I'd be happy to use them.

Thanks a lot.

**Comment by ebaauw** [comment]
They’re still in the old [ph.sh](https://github.com/ebaauw/ph.sh) repository.  I changed them to make use of `ph` from homebridge-hue-utils, but they’re still bash scripts.  I’m afraid the only documentation is in the scripts themselves.
