### ISSUE TITLE
Improve error handling for outlet CLI option

### ISSUE THREAD

**Issue by timbru31** [ebaauw/homebridge-hue-utils#5]
It would be a good addition to check the actual result of `const lights = await this.bridge.get('/lights')` (https://github.com/ebaauw/homebridge-hue-utils/blob/master/cli/ph.js#L554), because in case of an unexpected response the code fails when calling `.substr` on `type` (https://github.com/ebaauw/homebridge-hue-utils/blob/master/cli/ph.js#L577)

Background: my deCONZ runs on another port, so the GET for /lights returned an HTML response from the webserver that runs on port 80

**Comment by ebaauw** [comment]
The check whether we actually deal with a Hue bridge or deCONZ gateway is generic for all `ph` commands.  It should be in 
https://github.com/ebaauw/homebridge-hue-utils/blob/e2ca53b9cdb471aecdb2a72559ee6a45661c3b47/cli/ph.js#L342

You should use `ph -H 127.0.0.1:8080 outlet` (or whatever port you’re using) or set PH_HOST.

**Comment by ebaauw** [comment]
Hm, I already had a `try`/`catch` there, but instead of handling the error, I simply ignored it.  Can't recall why...  Anyways, now reporting the error and exiting.

**Comment by timbru31** [comment]
Your commit looks good! I'll test it later today at home.
