### ISSUE TITLE
dc_eventlog connection refused and error

### ISSUE THREAD

**Issue by ooii** [ebaauw/homebridge-hue-utils#6]
Hi Eric,

While trying to debug some rules, I figured out that `journalctl -au dc_eventlog --follow | grep -i "/sensors/"` has no output. Executing `dc_eventlog` results in `error: connect ECONNREFUSED 127.0.0.1:443` which is expected since `deConz` is running at `192.168.0.11:80`. Note that i have an `env`variable set as:`$PH_HOST 192.168.0.11:80`.
When I force the host with `dc_eventlog -H 192.168.0.11:80`, I have `error: Unexpected server response: 200`.
That's very new behavior, maybe introduced by deconz v2.05.39?
I'm running `homebridge-hue-utils v1.0.5`.

Thanks for your help.

**Comment by ebaauw** [comment]
The websocket is at port 443 by default, so you don’t want to specify port 80 with `-H`.

**Comment by ooii** [comment]
OK, I already made the mistake of thinking that the websocket is also on port 80. But it is not on port 443 neither: `error: connect ECONNREFUSED 10.0.1.11:443` but on 8088. Sorry for that.
Everything was my mistake, `dc_eventlog` was not running anymore as a service and the service file has disappeared (or never existed). Anyway, now I have a service running on the right port and I'm seeing the messages.
Thanks for your help (as usual).
